owner: playerdata
repo: playerdata-status

sites:
  - name: PlayerData API
    url: https://app.playerdata.co.uk/api/liveness
  - name: PlayerData Web App
    url: https://app.playerdata.co.uk
  - name: PlayerData Website
    url: https://www.playerdata.co.uk

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.playerdata.co.uk
  logoUrl: https://raw.githubusercontent.com/playerdata/playerdata-status/master/static/playerdata-symbol.jpg
  name: PlayerData Status
  introTitle: "PlayerData Service Status"
  introMessage: |
    Current status for PlayerData services.

    Something wrong? Contact
    <a href="mailto:support@playerdata.co.uk">support@playerdata.co.uk</a>.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
