owner: ball-hayden
repo: playerdata-status

sites:
  - name: PlayerData API
    url: https://app.playerdata.co.uk/api/liveness
  - name: PlayerData Web App
    url: https://app.playerdata.co.uk
  - name: PlayerData Website
    url: https://www.playerdata.co.uk

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /playerdata-status
  logoUrl: https://raw.githubusercontent.com/ball-hayden/playerdata-status/master/static/playerdata-symbol.jpg
  name: PlayerData Status
  introTitle: "PlayerData Service Status"
  introMessage: |
    <p>Current status for PlayerData services.</p>

    <p>
      Something wrong? Contact
      <a href="mailto:support@playerdata.co.uk">support@playerdata.co.uk</a>
    </p>
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
